MapServer/MapServer-documentation

en/mapfile/label.txt
Update for the docs to clarify the behaviour now that the scaling issue is fixed (thanks @tbonfort !)
=> Clarify label OUTLINEWIDTH w.r.t. mapserver/mapserver#4942

en/mapscript/mapscript.txt, en/mapscript/php/phpmapscript.txt
This PR updates the documentation for colorObj in SWIG- and PHP-
Mapscripts to reflect the alpha component, including the
extended methods and changed signatures introduced in
PR mapserver/mapserver#5078
=> Update documentation regarding color alpha values

en/cgi/mapserv.txt
I was naively using mapserv cgi to test WMS requests.
Only, after I lost quiet some time and with help of people from mailing list: <http://lists.osgeo.org/pipermail/mapserver-users/2015-May/077860.html>  it turned out that WMS output prepends 3 extra lines indicating the mime-type (is this a bug or a feature?). 
This pull request indicates one way to deal with this. Hope it helps also others.
=> add example with OGC WMS requests

en/mapcache/caches.txt
The syntax for min/max-zoom uses a dash, fixed the documentation in this PR.
=> Fixed syntax for min/max-zoom of composite cache

en/mapcache/caches.txt
Spelling corrections, some punctuation corrections/improvements, changes for
internal consistency, capitalization of proper (e.g. company or software)
names, etc.
=> Some light copy editing in MapCache cache-types doc

en/mapcache/caches.txt, en/mapcache/install.txt
- Remove periods from the ends of text fragments that are not sentences, and add
final periods to those that are.
- Use consistent initial caps in section headings.
- Replace some words with more colloquial alternatives (e.g. replace
"occurrences" with "cases").
- Capitalize formal product names.
- Improve spelling, punctuation and grammar.
=> Some copy editing in the installation and cache-types sections

Makefile
The language code (uk) triggers some issue with the country code (uk).
We remove it as there is 0% translated for this language.
Fix #150
[build_translations]
=> Remove Ukraine translation

en/mapfile/class.txt, en/mapfile/cluster.txt, en/mapfile/composite.txt, en/mapfile/layer.txt, en/mapfile/outputformat.txt
- Standardise use of pipe for parameter options
- Add in missing keywords
These allow easier parsing of docs to extract parameters and Mapfile keywords.
=> Standardise Mapfile keyword and parameter docs

en/mapfile/map.txt
Docs currently mention GDAL.OGR config settings are documented elsewhere, but the PROJ ones are only mentioned in the DEBUG doc.
=> Add in PROJ_DEBUG CONFIG setting

en/mapfile/map.txt
For completeness - the OUTPUT format wasn't listed as a keyword.
=> Add OUTPUT format keyword

en/mapcache/config.txt
* remove star at the start of the line for description of source example
* update sources list
=> Typo and missing info for sources list

en/ogc/wms_server.txt
Make wms layer groups requestable by default (GetMap).
Linked to https://github.com/mapserver/mapserver/pull/5371
=> Make wms layer groups requestable

en/glossary.txt
The spelling of MapServer was wrong in Glossary
=> Wrong Spellings

en/mapfile/style.txt
Spelling of MapServer was wrong in STYLES.
=> Wrong Spelling

en/mapcache/dimensions.txt
After spending the day trying to get dimensions in MapCache running I've created a draft docs page from going through the mailing list, the migration guide, the sample MapCache config file, and trial and error. 
I've not used the TIME dimension functionality so don't have many details here, beyond linking to the RFC (and noting the new 1.6 syntax). 
There is also a reference to Assembly Dimensions in the migration guide, but I can't find many details on what this is for (presumably merging tiles together?). 
Any updates to the above parts of the docs very welcome. 
The Sphinx rendered page rendered can be seen at [http://geographika.net/mapserver_docs/mapcache/dimensions.html](http://geographika.net/mapserver_docs/mapcache/dimensions.html)
=> Add Dimensions documentation

en/mapfile/style.txt
See https://github.com/mapserver/mapserver/issues/3917. Most of text taken from http://trac.osgeo.org/mapserver/attachment/ticket/1305/doc.patch
=> Add in missing COLORRANGE, DATARANGE, RANGEITEM keywords to STYLE. 

en/mapfile/layer.txt
Fix #226
In some use case, we need to filter data before the final query in order to
avoid to get too much data in a subquery.
=> Add information about !BOX! variable

en/development/rfc/ms-rfc-121.txt
This update follows @tbonfort's [comment on mapserver-dev](https://lists.osgeo.org/pipermail/mapserver-dev/2018-July/015446.html) mailing list.
=> Add a section to RFC-121about backward compatibility issue on time dimension declaration

en/ogc/ogc_support.txt, en/ogc/wms_client.txt
Companion PR to update documentation to reflect support for WMS 1.3.0 as client in mapserver/mapserver#5547
Should not be merged until/unless mapserver/mapserver#5547 is also accepted (and then to the appropriate branch - either master and/or 7.0 as for mapserver/mapserver#5547)
=> Update WMS Client documentation for support of 1.3.0

en/mapcache/config.txt
This issue #254 says to add a note "The MapCache configuration file is only read when the Apache web server starts and the MapCache module is loaded. If you modify this file you will have to restart Apache for the changes to take effect." so I added it!
=> Note Added as per issue #254

en/development/rfc/ms-rfc-13.txt
Hi Guys This link is no longer exist. Not found Error 403 
Link is this :- http://www.opengeospatial.org/functional/?page=swe
So I have removed the older one and added the correct.
Here is the corrected link :-https://www.opengeospatial.org/projects/initiatives/swe_rfi
=> Updated OpenGeospatial Link

_templates/indexsidebar.html
In this 2 images don't have an alt text and usually "alt tags help visually impaired people and search engines to figure out what is shown in an image. so It is required to have an alt text for every image".
Images that does not have are :- _static/OSGeo_project.png,_static/foss4g2018.png
=> Added alt attribute to IMG tag

en/development/rfc/ms-rfc-70.txt
After going through a long documentation. i notice that this link  has no connection.
so please remove this link :- http://tinyows.org/trac/wiki/LibxmlSchemaGmlBug
=> Removing broken link :- http://tinyows.org/trac/wiki/LibxmlSchemaGmlBug

en/mapfile/map.txt
The type of the attribute defresolution was not coherent with the code. In the cpp code is as a double and in the docs was shown as an int.
=> defresolution type correction

en/basemaps/install.txt
https://osmdata.openstreetmap.de/ should be used.
=> change url

en/output/tile_mode.txt
The following errors are currently in the Travis builds:
```
home/travis/build/mapserver/docs/en/output/tile_mode.txt:123: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/home/travis/build/mapserver/docs/en/output/tile_mode.txt:170: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
/home/travis/build/mapserver/docs/en/output/tile_mode.txt:223: WARNING: Could not lex literal_block as "guess". Highlighting skipped.
```
=> Set code language to HTML on Tile Mode page

en/mapfile/template.txt, en/output/template_output.txt
Creating against master as this is a new feature not in 7.4. 
It details the new padding item template format option at https://github.com/mapserver/mapserver/pull/5890 along with an example of a use case - RST tables. Template examples doc also restructured for clarity.
=> Add new padding item format option and RST table example

en/mapfile/expressions.txt
Previously the docs implied all individual parts of an expression required brackets. 
See https://github.com/mapserver/mapserver/pull/5897 for tests and discussion at https://github.com/geographika/mappyfile/issues/85
=> Add clarifications with regards to brackets and EXPRESSIONS

en/mapfile/expressions.txt
As reported at https://github.com/geographika/mappyfile/issues/89 - add an example showing spaces in expressions and note that they are allowed.
=> Add example of spaces in expressions

en/development/tests/autotest.txt
In the documentation regarding how to demime results of tests it is mentioned as RESULT_NOMIME instead of RESULT_DEMIME
=> Corrects DEMIME documentation

en/mapcache/proxying.txt
MapCache issue [#173](https://github.com/mapserver/mapcache/issues/173) raises an inconsistency between documentation and actual implementation. This PR aims at fixing outdated documentation.
=> Upgrade MapCache proxying document to latest configuration syntax

en/mapcache/dimensions.txt
This is an attempt at fixing https://github.com/mapserver/mapcache/issues/228
From what I can tell, the `list_query` is used to list available times for (primarily?) the `demo` service. If the `list_query` returns strings or integers that aren't compatible with MapCache/MapServer then the `demo` service will just use those TIMEs as-is. This results in a `demo` that has invalid WMTS (or other service) requests.
I ran in to this because the way I read the documentation made it seem like I had to store and/or return epoch seconds from the database. I then switched to whatever the default is for python's sqlite3 module when storing datetime objects. That was invalid because it didn't include the `Z` at the end (my datetimes didn't have timezones).
Anyway this PR is my attempt at trying to …
=> Fix MapCache time dimension examples and explanation

en/mapfile/label.txt
This is documentation relative to the [following PR](https://github.com/mapserver/mapserver/pull/6052) in mapserver repository.
I noticed that the documentation for `[attribute]` in POSITION was missing, so I added it too.
=> add doc for [attribute] in ALIGN, OFFSET, and POSITION

en/mapfile/class.txt
This pull request is to get opinions on adding a `:name:` to all the Mapfile index directives. 
In summary all index directives would be updated from:
```
.. index:: 
pair: CLASS; BACKGROUNDCOLOR
```
to:
```
.. index:: 
pair: CLASS; BACKGROUNDCOLOR
:name: mapfile-class-background   
```
Links in the index will then change from https://mapserver.org/mapfile/class.html#index-1 which can change to a fixed URL - https://mapserver.org/mapfile/class.html#mapfile-class-background
This would form part of the updates to the MapScript API documentation updates - see [here](https://github.com/mapserver/mapserver/pull/5870). Named index options allow an HTML link to be added from the MapScript docs to the relevant Mapfile keyword. 
I've asked a [question on …
=> Add name options to index directives

en/development/rfc/index.txt, en/development/rfc/ms-rfc-131.txt, en/mapcache/dimensions.txt
Following discussions on [[mapserver-dev] mailinglist](https://lists.osgeo.org/pipermail/mapserver-dev/2019-December/015973.html), this RFC proposes to allow filepaths in dimension values in MapCache.
=> RFC-131 MapCache allow path in dimension value

en/development/rfc/ms-rfc-132.txt
Create RFC to formalise proposed changes MapScript API docs which will require edits to header files, and a new mapscript requirement for the docs build process. 
The approach has been tested with sample output [here](http://www.geographika.net/mapserver_docs/mapscript-api/stub/mapscript.classObj.html#mapscript.classObj).
=> Add MS RFC 132: Update MapScript API Docs

en/mapfile/symbol.txt
Characters can also be set using HTML entity numbers e.g. the codes listed at https://entitycode.com/
See [this msautotest](https://github.com/mapserver/mapserver/blob/85e294e8c8ce3c9c455fea0137d4af1ee2feced0/msautotest/renderers/multilabel-leader.map) for example.
=> Add HTML Entity Character option

en/mapfile/label.txt
Add the GROUP keyword added in 6.2
See thread at https://lists.osgeo.org/pipermail/mapserver-dev/2020-July/016241.html and 6.2 release notes at https://mapserver.org/development/announce/6-2.html#complex-multi-label-symbol-symbology
=> Add FORCE GROUP keyword

en/ogc/wfs_server.txt
Updates related to https://github.com/mapserver/mapserver/pull/6137
Add that individual field metadata can be overwritten if required, and the MSSQL driver supports "gml_types" "auto". 
As this code change could change/break existing how GML is currently returned I've made the pull request against master, as I'm not sure if this should be backported.
=> Update how gml_types auto is handled

en/output/ogr_output.txt
Add docs about empty geometries in OGR output if https://github.com/mapserver/mapserver/pull/6138 is accepted.
=> Add comment about empty geometries

.github/workflows/check-crlf.yml
- issue with recent 'exclude' directories changes in the v1 release of erclu/check-crlf/pull/1, so fall back to v1.0.0 while issues are resolved.
=> fall back to earlier check-crlf version

en/ogc/layer_metadata.txt
cc @geographika 
Updates ISO metadata standards names per discussion at https://lists.osgeo.org/pipermail/mapserver-users/2020-October/081901.html (related: mapserver/mapserver#6166, mapserver/mapserver#6169).
=> update ISO metadata standards information

en/documentation.txt
- while working on the PDF today I noticed that the migration guide is not included
- in fact this was an old ticket #55
- this adds it to the documentation index
=> include migration guide in PDF (fixes #55) [build_translations]

en/development/rfc/index.txt, en/development/rfc/ms-rfc-133.txt
Pull request of an RFC on removing deprecated Mapfile keywords. 
Once added I'll send an email to the dev list. 
Should also be backported to 7.6?
=> Add new RFC on proposed Mapfile Syntax changes

en/mapfile/symbol.txt
Update documentation to take into account that IMAGE is used for SVG files as well as per:
https://mapserver.org/development/rfc/ms-rfc-73.html#usage-example
Are JPG files also supported? Couldn't find the relevant code to verify.
=> Update symbol.txt to mention use of SVG symbols

_static/sphinx.css, conf.py, en/development/documentation.txt, en/mapfile/index.txt, en/mapfile/label.txt, en/mapfile/layer.txt, requirements.txt
- enable the `versionremoved` Sphinx directive, using the [sphinx-removed-in](https://pypi.org/project/sphinx-removed-in/) extension
- add styling for the new  `versionremoved` and `removed-in` directives
- update the documentation guide
- minor updates: 
- add `versionremoved` to a few label & layer parameters
- add `versionadded` to BINDVALS in layer, to avoid users from digging into RFC for that info
=> enable versionremoved directive

en/announcements/2021-03-30-limit-mapfile-access.txt, en/announcements/announcements_archive.txt, en/announcements/index.txt, en/include/announcements.inc
- new directory: /announcements/
- will hold pointers to all announcements (advisories, sprints, events, etc)
- advisory file will be timestamped (YYYY-MM-DD-name.txt)
=> Rearrange announcements for the security advisory

en/basemaps/install.txt, en/basemaps/style.txt, en/cgi/controls.txt, en/input/raster.txt, en/installation/unix.txt, en/installation/v8.txt, en/installation/win32.txt, en/mapfile/expressions.txt, en/mapfile/layer.txt, en/mapscript/mapscript.txt, en/ogc/mapscript.txt, en/output/pdf.txt
- related to changes in https://github.com/MapServer/MapServer/pull/6264
- minor "MapServer" spelling
=> update for removal of LAYER DUMP in the 8.0 release

en/ogc/wms_server.txt, en/output/tile_mode.txt
- fixes https://github.com/MapServer/MapServer-documentation/issues/448
- related to https://github.com/MapServer/MapServer/pull/5199
=> update for TILED=TRUE for WMS GetMap requests

en/mapfile/label.txt
- caught through https://github.com/MapServer/MapServer/issues/6334 by @mrclBIE 
- initially implemented in the source code for the MapServer 7.2 release through https://github.com/MapServer/MapServer/issues/5198
=> correct default for label partials

en/mapscript/mapscript.txt
- also correct in the SWIG documentation
=> correct default label partials

en/mapcache/seed.txt
- mapcache_seed utility mentions 'scanline" as option for iteration-mode (but docs say "level-by-level")
=> MapCache: correct seeder usage for scanline/iteration-mode

en/development/changelog/changelog-7-0.txt, en/development/changelog/changelog-7-2.txt, en/development/changelog/changelog-7-4.txt, en/development/changelog/changelog-7-6.txt, en/environment_variables.txt, en/include/announcements.inc, en/optimization/limit_mapfile_access.txt
- references `CVE-2021-32062`
- documents new `MS_MAP_BAD_PATTERN` environment variable
=> update for CVE map path access

.travis.yml
- most communities have moved to irc.libera.chat
- recently Freenode servers & channels were reset. Future there is unknown.
=> update IRC network for build notifications

conf.py, en/include/labels.inc, en/mapfile/web.txt, en/mapscript/imagery.txt
With the update to Sphinx 4.1the [nitpick_ignore_regex](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpick_ignore_regex) option is available. This can filter out erroneous warnings from the MapScript Pyhon API docs (see #544). 
The `nitpick` option can be turned back on to check for broken references. 
In addition the pull request fixes a couple of broken references
=> Turn nitpick back on and fix some broken refs

en/installation/iis.txt, en/mapcache/caches.txt, en/mapcache/install.txt
- Full installation steps of the FastCGI MapCache application on IIS
- Minor addition on MapCache templating and dimensions
- Updates on the Mapsever IIS FastCGI setup (including a hint on working with MapServer 8.0)
=> Notes on configuration of MapCache and MapServer on IIS and FastCGI

en/tinyows/serverinstallation.txt
A small update to add the missing autoconf in TinyOWS install instructions from stable source.
=> Missing autoconf in TinyOWS install instructions from stable source.

.travis.yml, Makefile, _static/ribbon.css, _templates/layout.html, conf.py, scripts/travis_deploy_website.sh, scripts/travis_update_pages.sh
This pull request publishes any changes to the `main` branch to a new `gh-pages` branch which is then available online at https://mapserver.github.io/MapServer-documentation/
It does [not seem possible](https://github.community/t/can-i-publish-multiple-branches-of-a-repository-on-github-pages/10314/4) to publish different branches from the same repository to gh-pages, so a branch is used within `MapServer-documentation`. 
Currently the MapServer documentation workflow is to make pull requests to the "main" branch. This triggers a Sphinx build of the docs HTML output. 
This pull request then takes this output and copies it to the gh-pages branch. This is then available at https://mapserver.github.io/MapServer-documentation/ where it can be reviewed. In time it would be nice to set this up …
=> Generate GitHub pages from main branch

en/index.txt
- adds badge for the persistent (or 'concept') DOI, so we won't have to change the link for each release
=> add DOI badge

en/development/changelog/mapcache/changelog-1-12.txt, en/development/changelog/mapcache/index.txt, en/download_archives.txt, en/include/announcements.inc
- related to https://github.com/MapServer/mapcache/pull/279
=> update for MapCache 1.12.0-rc1 release

en/mapfile/class.txt, en/mapfile/cluster.txt, en/mapfile/composite.txt, en/mapfile/grid.txt, en/mapfile/label.txt, en/mapfile/layer.txt, en/mapfile/leader.txt, en/mapfile/legend.txt, en/mapfile/map.txt, en/mapfile/querymap.txt, en/mapfile/reference.txt, en/mapfile/scalebar.txt, en/mapfile/style.txt, en/mapfile/web.txt
Adds various min, max and range validation rules that are now checked when parsing a Mapfile as part of [#6458](https://github.com/MapServer/MapServer/pull/6458). 
Also adds in a missing Mapfile keyword `LAYER; MINFEATURESIZE`.
=> Document new Mapfile validation in #6458

en/mapcache/seed.txt
Document the new `-H` switch added in https://github.com/MapServer/mapcache/pull/262 and released in MapCache 1.12
=> Document MapCache seeder switch

en/mapfile/composite.txt
Description of the compfilter based on original info I read, is in this users-list entry by Thomas B.
https://lists.osgeo.org/pipermail/mapserver-users/2015-October/078298.html
Fixes:  Compfilter description is missing in the COMPISTE page #677
=> Added COMPFILTER to documentation

en/mapcache/install.txt, en/tinyows/serverinstallation.txt
- same fix applied for MapCache url also
=> minor TinyOWS GitHub url change

en/mapscript/python.txt
Changed `1rite` to `write` in function description.
=> Fix typo in mapscript/python

.travis.yml
This will download the new 8.0.1 MapScript Python wheel  from https://pypi.org/project/mapscript/8.0.1/ to automatically create the MapScript API documentation e.g. https://mapserver.org/mapscript/mapscript-api/stub/mapscript.mapObj.html#mapscript.mapObj
=> Update MapScript version to generate latest docs

.travis.yml
As noted in https://github.com/MapServer/MapServer/pull/6892 the Python MapScript uploaded to PyPI didn't contain the doxygen comments used to create the MapScript API docs. 
I've uploaded a new version to test.pypi.org with comments so switching to this should resolve the missing MapScript docs (see current live docs with empty comments: https://mapserver.org/mapscript/mapscript-api/stub/mapscript.mapObj.html#mapscript.mapObj
The Travis script to generate docs (added in #610) from the main branch was commented out in https://github.com/MapServer/MapServer-documentation/commit/85716ce75db8c9e0828cabfb9e4baf5dfee6334e. This means it is currently not possible to review changes added to main at https://mapserver.github.io/MapServer-documentation/ before backporting to the live docs (or to …
=> Switch to Python MapScript with comments

_static/custom.css, _static/sphinx.css, conf.py
Currently due to long constant names there are overlaps between the TOC and the content at https://mapserver.org/mapscript/mapscript-api/index.html
This pull request ensures a horizontal scrollbar is used (when required) to avoid this overlap.
I was hoping the local TOC could be modified on that page, but it does not appeat to be possible. Failed attempts included adding:
```
.. toctree::
:hidden:
:maxdepth: 2
.. contents:: Table of Contents
:local:
:depth: 2
```
And also trying to modify localtoc2.html similar to how the Read the Docs theme works with the [global TOC](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-navigation_depth), but this does not work with `toc`:
```
{%- if display_toc %}
<h3>{{ _('Current Table Of Contents') }}</h3>
{{ toc(maxdepth=2) }} …
```
=> Add horizontal scrollbar to TOC when required

conf.py, en/development/rfc/ms-rfc-134.txt, requirements.txt
- also removes the `sphinxemoji` extension, to use raw hex codes instead (one less extension to support each upgrade)
=> upgrade to Sphinx 7.2.2

en/faq.txt, en/mapfile/outputformat.txt
cf discussion thread of https://lists.osgeo.org/pipermail/mapserver-dev/2023-September/016991.html where users are confused by the mention of those removed-for-long features
=> Remove outdated mentions of GIF, IMAGEMODE=PC256 and GD

.travis.yml, en/mapscript/mapscript-api/constants/config.rst, en/mapscript/mapscript-api/constants/connection.rst, en/mapscript/mapscript-api/constants/error.rst, en/mapscript/mapscript-api/constants/function.rst, en/mapscript/mapscript-api/constants/index.rst, en/mapscript/mapscript-api/constants/legend.rst, en/mapscript/mapscript-api/constants/missing.rst, en/mapscript/mapscript-api/constants/scalebar.rst, en/mapscript/mapscript-api/constants/tokenbinding.rst, en/mapscript/mapscript-api/constants/version.rst, en/mapscript/mapscript-api/functions.rst, requirements.txt, scripts/mapscript-docs/ReadMe.rst, scripts/mapscript-docs/constants.py
- Re-run `constants.py` file to add new constants to the API docs pages. 
- Add mapscript to requirements as mentioned in #836, and remove missing function pages. 
- Update ReadMe to use PowerShell rather than Windows CMD.
=> MapScript Documentation Updates

en/development/dev_practices.txt, en/development/index.txt
Heavily borrowed from https://gdal.org/development/dev_practices.html
This introduces how to install & use pre-commit now
=> Add a development practices page

requirements.txt
As part of the changes in #839 I incorrectly used a mapscript library without the autogenerated comments. 
This update uses a version of MapScript from test.pypi that has comments so the MapScript documentation is correctly generated. 
I can correct this for the next MapServer release, until then the test version will work.
=> Use annotated mapscript library

en/optimization/debugging.txt
When working on a Linux OS, debugging a MapFile while using the `/tmp` directory can be misleading for people who are not aware about systemd private directory security, i.e. putting `/tmp/ms_error.txt` in the MapFile does not actually output the log at that exact location on your OS system.  It outputs it in a private directory generated by systemd for the service used (in my case, it was Apache).
So, this patch is about documenting this to avoid people that were unaware of that (like me) to fall in that trap again in the future.
=> Adjust debugging MapFile doc about systemd private tmp dir

en/mapfile/legend.txt, en/mapfile/scalebar.txt
As noted in the thread at https://lists.osgeo.org/pipermail/mapserver-dev/2023-October/017023.html - the SCALEBAR and LEGEND TRANSPARENT keywords are still required to create transparent scalebars and legends on non-transparent maps.
=> Update TRANSPARENT keywords

.github/workflows/build.yml
This ensures https://mapserver.org/ is only updated by changes to the active `branch8-0`. 
The GHA logic was ported from TravisCI, but it seems changes to the main branch were also causing the website to update - see the history of https://github.com/MapServer/mapserver.github.io/commits/master/ and for example this pull request to main that was deployed - https://github.com/MapServer/MapServer-documentation/commit/9e8efe092f009540017b7c8e7edb69668a6d8ca8
Typically backports were then also applied which re-deployed branch-8-0 on top of this. 
This pull request ensures only merges to branch-8-0 get deployed.
=> Only deploy the active branch-8-0 to mapserver.org

en/mapcache/http.txt
Mapcache now supports basic authorization for http(s) requests. This PR shuld be merged after https://github.com/MapServer/mapcache/pull/328 to document the new feature.
=> mapcache: document authorization use

en/ogc/wms_server.txt
this adds the use of aliases to the options to hide the &map=xxx parameter from querystring
I wonder if it makes sense to deprecate other suggested methods
=> introcuce use of alias on wms_server

en/mapfile/config.txt
Add note for the update in https://github.com/MapServer/MapServer/pull/6862 that allows keys in the ``CONFIG`` file to be used by all types of requests.
=> Add note about CONFIG MAPS keys in URLs

conf.py, requirements.txt
The Service Providers page is currently broken (in terms of layout and random ordering) as JQuery no longer seems to be present in the deployed docs at https://mapserver.org/community/service_providers.html#service-providers
`Uncaught ReferenceError: $ is not defined`
This pull request adds back JQuery using the Sphinx plugin https://pypi.org/project/sphinxcontrib-jquery/ which fixes the issue.
=> Add JQuery to fix broken Service Providers page

en/ogc/wcs_format.txt
fixed typo for Celsius in the WCS_format page (s/Celcius/Celsius/)
=> fixed typo for Celsius in the WCS_format page (s/Celcius/Celsius/)

en/ogc/ogc_api.txt
- related to https://github.com/MapServer/MapServer/issues/6752
=> add CMake -DWITH_WFS note for OGCAPI Features

en/mapscript/mapscript-api/constants/compop.rst
Documentation builds for the 8.2 branch are reporting the following errors:
```
AttributeError: module 'mapscript' has no attribute 'MS_COMPOP_HSL_HUE'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 210, in import_object
obj = attrgetter(obj, mangled_name)
...
```
I think this is due to https://github.com/MapServer/MapServer-documentation/pull/914 being merged in May 2024, prior to the 8.2 documentation branch being created. When the branch was created from `main` this pull request was included. 
The references to 8.4 functionality are live at https://www.mapserver.org/mapfile/composite.html (which isn't an issue). This …
=> Remove mapscript docs referencing 8.4 functionality from 8.2 branch

.github/workflows/build.yml, scripts/ci_deploy_website.sh
When docs are built and pushed to https://github.com/MapServer/mapserver.github.io/ old HTML files are never removed.
There are several published pages which have been removed from https://github.com/MapServer/MapServer-documentation/ that are still online. For example:
- https://www.mapserver.org/mapscript/mapscript.html
- https://mapserver.org/previousversions.html
- https://mapserver.org/zh_cn/mapfile/map.html
- https://www.mapserver.org/mapfile/labelencoding.html
This pull request adds a step to delete all the files from the https://github.com/MapServer/mapserver.github.io/ repo if a pull request includes `[build_translations]` in the commit message. This tag is already used to trigger rebuilds of all languages. 
We can only remove all files when rebuilding all languages, otherwise …
=> Clean repository when all languages are rebuilt

en/development/documentation.txt
Adding `[build_translations]` in the commit message should trigger a rebuild of the translated documents. See #966.
=> Rebuild translated MapServer documentation

en/mapfile/config.txt, en/ogc/wms_server.txt
added in https://github.com/MapServer/MapServer/pull/7191
=> Document MS_WMS_ERROR_STATUS_CODE

en/cgi/openlayers.txt, en/mapfile/config.txt, en/optimization/environment_variables.txt
Docs updated for pull request at https://github.com/MapServer/MapServer/pull/7218, including the new `MS_OPENLAYERS_CSS_URL` environment variable. 
Not for backporting as OL2 and OL10 templates are incompatible, so this will be part of a future MapServer 8.6 release.
=> Updated docs for OpenLayers 10.4 MapServer Viewer

en/mapfile/map.txt, en/ogc/wms_server.txt
Documents the vendor MAP_RESOLUTION parameter for MapServer WMS. 
As discussed in https://github.com/mapserver/mapserver/issues/5350
It is also used by OpenLayers - see discussion at https://github.com/openlayers/openlayers/issues/14391 if [serverType](https://openlayers.org/en/latest/apidoc/module-ol_source_wms.html#~ServerType) is set and `hidpi` is set to `true`.
Pull requests also fixes some index links.
=> Document MAP_RESOLUTION WMS vendor specific parameter

en/ogc/wfs_server.txt, en/output/ogr_output.txt
This build flag was removed in MapServer 8.0 (see https://github.com/MapServer/MapServer/pull/6263), and so Z values are now always available.
A few other typos fixed in the surrounding docs.
=> Remove references to USE_POINT_Z_M

en/input/raster.txt
`PROCESSING "CLASSIFY_SCALED=TRUE"` was added in https://github.com/MapServer/MapServer/pull/5834 to resolve https://github.com/mapserver/mapserver/issues/5830 and merged in 7.6.
=> Add PROCESSING CLASSIFY_SCALED directive
