MapServer/MapServer-documentation

en/mapfile/layer.txt
en/output/index.txt
en/output/kerneldensity.txt

Add kernel density documentation from RFC108 to Fix #108

Add kernel density documentation

---

en/ogc/wcs_server.txt

Related to https://github.com/mapserver/mapserver/issues/5047

Improving WCS 2.0 subsettingCrs docs

---

en/mapcache/config.txt

port https://github.com/mapserver/docs/pull/129 to branch 7

extent expected in lonlat + grid origin tag

---

en/mapcache/locks.txt
en/mapcache/proxying.txt
en/mapcache/seed.txt
en/mapcache/services.txt
en/mapcache/sources.txt

Spelling, punctuation, capitalization, elimination of trailing whitespace, etc.

Copy editing in locks, proxying, seed, services, sources docs

---

en/mapfile/web.txt

Fixed very minor typo

---

en/mapcache/sources.txt

mapcache gdal source (gdal wmts driver)

Mapcache wmts source

---

en/mapcache/config.txt

Here's the documentation for the ruleset feature in PR: https://github.com/mapserver/mapcache/pull/150
Hopefully it's understandable.

documentation of mapcache ruleset feature

---

conf.py

Relates to https://github.com/mapserver/docs/issues/125

Set the theme explicitly so the relbar displays

---

en/ogc/wms_server.txt

add metadata to optionally not emit root layer name in WMS Capabilities XML

---

en/ogc/index.txt
en/ogc/layer_metadata.txt
en/ogc/sos_server.txt
en/ogc/wcs_server.txt
en/ogc/wfs_server.txt
en/ogc/wms_server.txt

Based on http://mapserver.org/development/rfc/ms-rfc-82.html as implemented in master in https://github.com/mapserver/mapserver/pull/5412.

add RFC82 documentation

---

en/development/rfc/ms-rfc-82.txt

Updates RFC82 given it is now implemented in master branch.

update RFC 82

---

de/mapfile/layer.txt
en/mapfile/layer.txt
translated/ar/mapfile.po
translated/de/mapfile.po
translated/el/mapfile.po
translated/es/mapfile.po
translated/fr/mapfile.po
translated/id/mapfile.po
translated/it/mapfile.po
translated/ja/mapfile.po
translated/nl_NL/mapfile.po
translated/pl/mapfile.po
translated/ru/mapfile.po
translated/sq/mapfile.po
translated/tr/mapfile.po
translated/uk/mapfile.po
translated/zh/mapfile.po

fixed TRANSFORM parameters according to the source code
https://github.com/mapserver/mapserver/blob/4ea78eb919147924bbf66d426a0bb8000f94c768/mapfile.c#L4913

lc|cc|lr => cl|cc|cr

---

en/mapfile/web.txt

* `MINTEMPLATE` -> `MINTEMPLATE [file|url]`
* `TEMPPATH` -> `TEMPPATH [path]`
Superseed #172 by @dnltsk

Fix web object (Mapfile)

---

en/mapfile/feature.txt

Was attempting to do this using -99 "magic" numbers as per symbols

Add note about multipart features

---

en/installation/iis.txt

Rewrite IIS MapServer configuration doc

---

en/mapscript/php/phpmapscript.txt

pointObject -> pointObj

---

en/mapscript/php/phpmapscript.txt

Fixing errors and inconsistencies in the PHP mapscript docs that I found when I was trying to generate a stub file from the documentation

PHP mapscript documentation fixes

---

en/cgi/controls.txt

Add TILE mode, and COORDINATE mode details

---

en/mapcache/config.txt

According to lib/tileset.c#L498

Document default tile expiration values

---

en/mapfile/class.txt

Logical expressions Documentation was wrong so i corrected it to "Logical expressions allow the building of fairly complex tests based on one or more attributes.".

Correcting Logical expressions

---

en/mapfile/outputformat.txt

Spelling of MapServer was wrong in OUTPUTFORMAT

Wrong Spelling

---

en/output/ogr_output.txt

Form is simple not single - make sure this is clear in the text.

Clarify output form keyword

---

en/ogc/inspire_dl.txt
en/ogc/wcs_server.txt

Additional documentation for changes introduced for RFC 120.

RFC 120 documentation

---

en/development/rfc/index.txt
en/development/rfc/ms-rfc-121.txt

This pull request incorporates RFC-121: PostgreSQL and ElasticSearch Support in MapCache dimensions.

[MapCache] Submit RFC-121 on MapCache dimension back-ends

---

en/mapfile/label.txt

https://github.com/mapserver/mapserver/pull/5634

Document label-wrap-fix

---

en/mapfile/expressions.txt

Also correct spelling and update date

Add in missing modulus operator - see #252

---

en/development/rfc/index.txt
en/development/rfc/ms-rfc-124.txt

This RFC proposes to address some issues on MapServer SLD support. This is currently a work in progress that will span over the year. Still, early comments will be highly appreciated.

Submit RFC 124 on MapServer SLD Improvements

---

en/ogc/wfs_server.txt

Add notes on which drivers allow WFS sorting. 
Related to https://github.com/mapserver/mapserver/pull/5833

Add WFS Sorting notes

---

en/ogc/wfs_server.txt
en/ogc/wms_server.txt
en/output/ogr_output.txt

Related to https://github.com/mapserver/mapserver/pull/5910 (so do not merge this PR before the MapServer one)

Mention new DateTime and Time data types

---

en/mapfile/projection.txt

Inspired by https://lists.osgeo.org/pipermail/mapserver-users/2019-November/081494.html

Rasters in different projections supported by tileindex TILESRS

---

en/mapfile/union.txt

Clarifying this in the hope that I can save someone (or even a future self) from going down the wrong path.

Clarify that union layer is not for rasters

---

en/mapcache/config.txt
en/mapcache/dimensions.txt

This pull requests aims at improving MapCache documentation with respect to latest revisions.

Fix oversights and add new features in MapCache documentation

---

en/development/rfc/ms-rfc-130.txt
en/mapcache/caches.txt

This PR proposes to add documentation to MapCache Caches about Z-top cache structure (see [RFC 130](https://mapserver.org/development/rfc/ms-rfc-130.html)).

Update MapCache documentation wrt. RFC 130

---

en/ogc/wcs_server.txt
en/ogc/wfs_server.txt
en/ogc/wms_server.txt

Related to https://github.com/mapserver/mapserver/pull/6031

Document wms_metadataurl_list, wfs_metadataurl_list and wcs_metadatalink_list

---

en/mapfile/expressions.txt
en/ogc/sld.txt

This update documents changes proposed in MapServer pull request [#6017](https://github.com/mapserver/mapserver/pull/6017). Both PR should be approved or rejected simultaneously.

Update documentation relative to SLD <Label> improvements

---

en/mapcache/seed.txt

added missing commandline options to mapcache seeder documentation

add commandline options to mapcache seeder documentation

---

en/mapfile/symbology/construction.txt

Trivial updates to the text that describes some open "issues" for advanced symbol construction.

Symbol construction - issues update

---

en/input/vector/mssql.txt

Remove 2008 references (to remove confusion over if later versions are supported), and add driver notes.

MSSQL Input Updates

---

en/mapfile/label.txt

See https://github.com/mapserver/mapserver/pull/5831 and in particular https://github.com/mapserver/mapserver/pull/5831/commits/fc07dd9168d06a2fbca3e833d0ec56959c52449b

Update LABEL SIZE with expression option

---

en/development/announce/6-2.txt
en/mapfile/label.txt

Link to release notes which has an additional image as an example (see #337). 
Fix a couple of typos.

Add link to release notes for FORCE GROUP param

---

de/introduction.txt
de/mapfile/map.txt
de/utilities/shptree.txt

- smaller test of recent Github master/naming changes

update for repository name changes [build_translations]

---

en/MIGRATION_GUIDE.txt

- update migration guide for recommended PROJ/GDAL combinations
- also test backport & Travis CI processes....

update recommended PROJ/GDAL combo [build_translations]

---

.github/workflows/check-crlf.yml

- adds Github action to check for linefeeds: https://github.com/marketplace/actions/check-crlf

add check-crlf github action

---

en/mapscript/php/phpmapscript.txt

add versionadded for toHex(), setHex()

---

en/mapfile/class.txt

Fix TITLE index and ref

---

en/mapscript/php/phpmapscript.txt

add insertStyle() to PHP MapScript (#237)

---

en/development/rfc/ms-rfc-105.txt
en/development/rfc/ms-rfc-114.txt
en/development/rfc/ms-rfc-124.txt
en/development/rfc/ms-rfc-13.txt
en/development/rfc/ms-rfc-70.txt
en/faq.txt
en/glossary.txt
en/input/vector/gml.txt
en/input/vector/kml.txt
en/input/vector/wfs.txt
en/installation/unix.txt
en/mapcache/dimensions.txt
en/ogc/filter_encoding.txt
en/ogc/index.txt
en/ogc/mapcontext.txt
en/ogc/sld.txt
en/ogc/sos_server.txt
en/ogc/wcs_server.txt
en/ogc/wfs_client.txt
en/ogc/wfs_server.txt
en/ogc/wms_client.txt
en/ogc/wms_dimension.txt
en/ogc/wms_server.txt
en/ogc/wms_time.txt
en/output/svg.txt
en/tutorial/example1-7.txt
zh_cn/faq.txt

- replace old url of "opengeospatial.org" with new url "ogc.org"

change to use ogc.org domain

---

.github/workflows/check-crlf.yml

- update Github action to latest version for check-crlf

bump check-crlf version

---

en/mapcache/config.txt

Did not find this MapCache metadata section documented anywhere. Hope it is not a duplicate.

Add docs for MapCache metadata for WMTS services

---

en/ogc/wfs_server.txt

- document new 'wfs_geometry_precision' metadata for WFS Server
- related to https://github.com/MapServer/MapServer/issues/6208

WFS precision metadata changes

---

en/mapfile/style.txt

… due to https://github.com/MapServer/MapServer/pull/6225

style.txt: update description of ANTIALIAS

---

en/mapfile/union.txt

- related to changes made back in https://github.com/MapServer/MapServer/issues/4082

UNION: update predefined layer/group field names

---

en/mapfile/symbol.txt

- thanks to @iljya for the research

add anchorpoint SVG width/height note

---

en/development/documentation.txt

- requested by @dmorissette through https://github.com/MapServer/MapServer-documentation/pull/450

enhance Sphinx version note to mention requirements.txt

---

en/development/documentation.txt

- from comments from @geographika & @dmorissette through https://github.com/MapServer/MapServer-documentation/pull/450

update Sphinx install notes in the Documentation Guide

---

en/development/documentation.txt
en/mapfile/style.txt

- missing from earlier update through https://github.com/MapServer/MapServer/issues/6219

add labelcenter to STYLE

---

en/optimization/tileindex.txt
en/utilities/tile4ms.txt

- add steps to handle case for data in various subdirectories

add steps for tileindex with subfolders

---

en/optimization/index.txt
en/optimization/limit_mapfile_access.txt

- related to recent push to promote tighter MAP= path security

initial new 'Limit Mapfile Access' document

---

en/development/rfc/ms-rfc-56.txt
en/environment_variables.txt
en/optimization/limit_mapfile_access.txt

- explanation of the Windows example expression was incorrect

clarify Windows ms_map_pattern expression

---

en/ogc/wxs_secure.txt

Adds a command line example for cert testing with a bundle file.

Add example of openssl and cert file

---

en/input/raster.txt
en/ogc/wxs_secure.txt
en/optimization/debugging.txt
en/optimization/mapfile.txt
en/optimization/raster.txt
en/optimization/vector.txt

- updates vector optimization steps with examples
- also minor updates to raster optimization

WIP: update vector optimization steps

---

en/optimization/debugging.txt

- also points to wiki and main site pages

debugging: add another GDAL variable example

---

en/development/tests/autotest.txt

minor msautotest wording

---

en/development/rfc/ms-rfc-133.txt

Updates on keywords, voting history and tickets

RFC 133 updates

---

en/cgi/runsub.txt
en/mapfile/map.txt

- mentioned in https://github.com/MapServer/MapServer/pull/6317

deprecate DATAPATTERN & TEMPLATEPATTERN

---

en/mapfile/web.txt
en/ogc/wms_client.txt
en/ogc/wms_server.txt
en/output/tile_mode.txt

- also documents `mode=tile` metadata in the mapfile WEB object

minor update to WMS-client

---

en/development/release/release-plan-8.0.txt

update 8.0 release dates, from wiki

---

en/documentation.txt
en/optimization/environment_variables.txt
en/optimization/index.txt
en/optimization/mapfile.txt

- having the environment variables document in the optimization folder makes more sense
- also fixes mapfile tuning image

move environment variables doc into /optimization

---

en/community/irc.txt
en/introduction.txt

- most communities have moved to irc.libera.chat
- recently Freenode servers & channels were reset.  Future there is unknown.

update IRC channel

---

README.md

- adds missing README in the repository, for documentation contributions

add general README, for contributions

---

en/mapfile/leader.txt

- spawned by @lucadelu
- tested and confirmed that points, lines, polygons work with label LEADER

correct supported layer types for label LEADER

---

.github/workflows/backport.yml

- upgrade Backport action `m-kuhn/backport` to recent release

upgrade Backport action

---

en/input/vector/index.txt
en/input/vector/postgis.txt

- related to https://github.com/MapServer/MapServer/issues/6367

add OID note for PostGIS connections

---

requirements.txt

- also fixes many errors related to outdated contrib extensions

upgrade to Sphinx 4.1.0 release

---

requirements.txt

- also removed workaround for the contribs regression

upgrade Sphinx to 4.1.1

---

en/development/release/release-plan-8.0.txt

- as discussed in today's PSC meeting

update 8.0 release schedule

---

en/development/rfc/index.txt
en/development/rfc/ms-rfc-135.txt

- this will replace the wiki draft at https://github.com/sdlime/mapserver/wiki/MapServer-8.0-Config-File
- (will also note this on the wiki page)

add RFC 135 / MapServer Config file

---

requirements.txt

- upgrades Sphinx to 4.2.0 release
- upgrades sphinxemoji to 0.1.9 release

bump Sphinx

---

en/community/irc.txt

- syntax has changed for WebChat link through Libera.chat

update IRC webchat link

---

en/community/lists.txt
en/development/bugs.txt
en/development/rfc/ms-rfc-133.txt
en/development/rfc/ms-rfc-39.txt
en/introduction.txt
en/ogc/inspire_dl.txt

- point to other options as Nabble is shutdown

update mail archive search links

---

_static/ol.js
en/index.txt

- updates map on homepage
- leverages MapCache-git-main, MapServer-git-main, and OSM (Minnesota state)
- also leverages all the hard work put into demo.mapserver.org

update to map viewer on homepage

---

.github/workflows/irc_notify.yml

- adds build notifications as a GitHub action/workflow, to the IRC channel #mapserver
- from effort earlier on https://github.com/MapServer/MapServer/pull/6302

add IRC build notifications

---

en/index.txt

- from feedback received on the big effort: "wow, I love it, this viewer on the homepage should be near top of the page!".  My answer was "you're right, of course it should!" 🚀

promote map viewer

---

.github/workflows/irc_notify.yml

- related ticket filed: https://github.com/rectalogic/notify-irc/issues/6

disable IRC notice setting temporarily

---

requirements.txt

update for Sphinx 4.3.1 release

---

en/cgi/controls.txt
en/output/tile_mode.txt

See https://github.com/MapServer/MapServer/pull/6444

Document tilesize query parameter for mode=tile requests

---

requirements.txt

upgrade Sphinx

---

conf.py

update year in docs

---

.github/workflows/backport.yml

- more improvements to backport failure case

bump Backport action

---

en/ogc/wcs_server.txt

Documentation of https://github.com/MapServer/MapServer/pull/6456

wcs_server.txt: document wcs_outputformat_{OUTPUTFORMATNAME}_mdi_{DOMAIN}_{KEY}

---

en/input/vector/index.txt
en/input/vector/postgis.txt
en/ogc/wms_server.txt
en/optimization/raster.txt
en/optimization/vector.txt

- also minor changes to vector and raster optimization notes

minor improvements to PostGIS optimization notes

---

.github/workflows/backport.yml

- update to recent 1.2.7 release

update Backport action

---

en/ogc/wcs_server.txt

added per https://github.com/MapServer/MapServer/pull/6464

wcs_server.txt: document netCDF 3D output capabilities

---

en/input/vector/mssql.txt
en/mapfile/config.txt
en/mapfile/index.txt

Related to the new `CONFIG` file in https://github.com/MapServer/MapServer/pull/6303

Add docs for new CONFIG file

---

en/mapfile/validation.txt

- credit to files provided by Andrea Borruso through https://lists.osgeo.org/pipermail/mapserver-users/2022-February/082514.html

add run-time substitution expression example

---

en/announcements/announcements_archive.txt
en/development/changelog/mapcache/changelog-1-12.txt
en/download.txt
en/download_archives.txt
en/include/announcements.inc
en/mapcache/index.txt

- tags documentation for MapCache 1.12.0-final release
- @tbonfort I notice many pointers to your @terriscope.fr email address (especially on the MapCache index.txt), please let me know what address to use instead, if you wish

update for MapCache 1.12.0-final release

---

en/community/service_providers.txt

- fix Spatialys link
- fix AstunTech link
- @tbonfort this removes the broken link (http://www.terriscope.fr/) and your section.  Do you want it replaced with another company name?  Please let me know how to handle Terriscope here.
- will send out a public call now for more listed service providers...

[WIP] update service providers page

---

en/input/vector/geopackage.txt
en/optimization/vector.txt

- spurred by https://github.com/MapServer/MapServer/issues/6502

update GPKG and vector optimization notes

---

en/input/vector/flatgeobuf.txt
en/ogc/wfs_server.txt
en/optimization/vector.txt

- promote the use of the layer metadata `wfs_use_default_extent_for_getfeature`

promote use of wfs_use_default_extent_for_getfeature

---

en/errors.txt
en/faq.txt
en/mapfile/leader.txt
en/mapscript/php/by_example.txt
en/output/antialias.txt
en/output/flash.txt
en/output/imagemaps.txt

- adds missing extension as without is confusing for new users

add extension to old DATA examples

---

en/development/rfc/index.txt
en/development/rfc/ms-rfc-137.txt

- draft of native FlatGeobuf access for MapServer
- once ready, this document will be proposed to the Project Steering Committee
- related to MapServer/MapServer/pull/6520/

FlatGeobuf RFC document

---

en/ogc/wfs_server.txt
en/optimization/vector.txt

- from recent discussion on mailing list

promote use of gml_types metadata

---

en/input/raster.txt
en/mapfile/map.txt

- also minor raster example formatting changes

improve SHAPEPATH description

---

en/development/rfc/ms-rfc-137.txt

update RFC 137 / FlatGeobuf native support

---

en/development/rfc/ms-rfc-137.txt

- credit to @LarsSchy for the nudge

expand VERIFY_BUFFERS description

---

requirements.txt

- waited until the 5.0.2 release happened, which fixed many 5.0 regressions

upgrade to Sphinx 5.0.2 release

---

en/development/rfc/ms-rfc-132.txt
en/development/rfc/ms-rfc-134.txt
en/development/rfc/ms-rfc-135.txt
en/development/rfc/ms-rfc-136.txt
en/development/rfc/ms-rfc-137.txt
en/input/vector/flatgeobuf.txt
en/input/vector/index.txt

- related to https://github.com/MapServer/MapServer/pull/6520
- also updates various RFC voting results

update FlatGeobuf docs, various RFC statuses

---

en/development/rfc/ms-rfc-117.txt

deploy branch-8-0

---

en/glossary.txt
en/installation/unix.txt
en/introduction.txt
en/mapcache/services.txt
en/ogc/wms_client.txt
en/ogc/wxs_secure.txt
en/optimization/debugging.txt

- mostly done to trigger website rebuild

linkcheck changes

---

en/MIGRATION_GUIDE.txt
en/output/agg.txt

fix AGG link

---

en/mapfile/config.txt
en/ogc/ogc_support.txt
en/optimization/limit_mapfile_access.txt

- also adds OGC API to the "OGC Specification support" page

clarify MS_MAP_PATTERN requirements

---

en/development/announce/8-0.txt
en/mapfile/geomtransform.txt

- also fixes minor GEOMTRANSFORM warning

update 8.0-rc1 announcement

---

en/MIGRATION_GUIDE.txt
en/mapfile/index.txt
en/mapfile/layer.txt

- related to MapServer/MapServer/pull/6603

update layer NAME notes

---

en/input/vector/vector_field.txt

… added in https://github.com/MapServer/MapServer/pull/6610

UVRaster: document lon and lat attributes 

---

en/cgi/runsub.txt
en/mapfile/class.txt
en/mapfile/layer.txt
en/mapfile/outputformat.txt
en/mapfile/web.txt

See details in https://github.com/MapServer/MapServer/pull/6804
@sdlime - these updates should match the latest values in MapServer 8.0

Update list of parameters available for runtime substitution

---

en/mapcache/caches.txt
en/mapcache/index.txt
en/mapcache/install.txt

Should be merged after https://github.com/MapServer/mapcache/pull/293

MapCache: documentation of LMDB cache backend

---

en/mapfile/config.txt

See https://github.com/MapServer/MapServer/pull/6808

Remove MS_NO_VERSION "1" from sample config

---

LICENSE.md
README.md
en/copyright.txt

- add main license file to repo
- clarify the existing license of CC BY SA

clarify license for documentation

---

en/ogc/wms_time.txt

update wms-t postgis example per mapserver8

---

en/optimization/environment_variables.txt
en/optimization/limit_mapfile_access.txt

added per https://github.com/MapServer/MapServer/pull/6780

Document MS_CONTEXT_PATTERN and MS_CONTEXT_BAD_PATTERN

---

en/mapscript/mapscript-api/classes.rst

See #828. Can be merged once https://github.com/MapServer/MapServer/pull/6922 is merged.

Add link for reprojectionObj

---

en/mapfile/style.txt

Edit see mailing list posts: https://lists.osgeo.org/pipermail/mapserver-dev/2023-October/017010.html
and https://lists.osgeo.org/pipermail/mapserver-users/2023-October/083250.html

Remove incorrect versionremoved tags for STYLE MINSIZE and MAXSIZE

---

en/mapfile/template.txt

Template docs updated to include https://github.com/MapServer/MapServer/pull/7017
A couple of typos in the page also updated.

Add ignoremissing property to template docs

---

en/mapfile/label.txt

Updated docs for https://github.com/MapServer/MapServer/pull/6884 (not to be backported).

Add note about PRIORITY expressions for 8.2 release

---

en/mapfile/style.txt

See https://github.com/MapServer/MapServer/pull/6895

Add note about expressions for STYLE SIZE

---

.github/workflows/build.yml

Run build on all branches, but only deploy on `branch-8-0`.

Run GitHub Actions build on all branches

---

scripts/ci_deploy_website.sh

Left over from testing, and was fixed in main but not in backport to 8-0 branch

Update repo user

---

en/development/rfc/ms-rfc-138.txt

Added in implementation details, and feedback and voting history from the mailing list https://lists.osgeo.org/pipermail/mapserver-dev/2024-February/017105.html

RFC138 updates

---

en/download.txt

- credit to "ElNinijo" user for the recent updates to that repo

update Fedora/EPEL download description

---

conf.py
requirements.txt

- also remove the `sphinx-removed-in` extension, and use the new native `versionremoved` property

upgrade Sphinx to 7.3.7

---

en/mapfile/composite.txt
en/mapscript/mapscript-api/constants/compop.rst

As implemented in https://github.com/MapServer/MapServer/pull/7065

Document 4 new hsl-color, hsl-hue, hsl-luminosity and hsl-saturation operators

---

conf.py
requirements.txt

- adds a copy button to the top-right of all code blocks

add copybutton to code blocks

---

en/announcements/announcements_archive.txt
en/development/announce/6-2.txt
en/development/bugs.txt
en/development/editing/emacs.txt
en/development/rfc/ms-rfc-105.txt
en/development/rfc/ms-rfc-13.txt
en/development/rfc/ms-rfc-30.txt
en/development/rfc/ms-rfc-39.txt
en/development/rfc/ms-rfc-58.txt
en/development/rfc/ms-rfc-67.txt
en/development/rfc/ms-rfc-73.txt
en/development/rfc/ms-rfc-75.txt
en/faq.txt
en/input/vector/arcsde.txt
en/input/vector/ogr.txt
en/introduction.txt
en/mapfile/layer.txt
en/mapfile/projection.txt
en/mapscript/php/by_example.txt
en/mapscript/php/index-5.6.txt
en/mapscript/php/phpmapscript.txt
en/ogc/filter_encoding.txt
en/ogc/sld.txt
en/ogc/wms_dimension.txt
en/optimization/debugging.txt
en/output/flash.txt
en/output/kml_output.txt
en/output/pdf.txt

- also improved the SLD filter encoding services on demo.mapserver.org

Spelling, links, and demo fixes

---

en/ogc/ogc_api.txt

* See https://github.com/MapServer/MapServer/pull/7037
Resolves MapServer/MapServer#7036

Document ows_schemas_location for OGC API Features

---

en/mapfile/layer.txt
en/ogc/sld.txt

Documentation for RFC 138 - https://mapserver.org/development/rfc/ms-rfc-138.html
See https://github.com/MapServer/MapServer/pull/7034 for implementation.

Documentation for RFC138

---

requirements.txt

- also upgrade other dependencies

upgrade Sphinx to 7.4.3

---

en/input/raster.txt
en/mapfile/layer.txt

Refs https://github.com/MapServer/MapServer/pull/7069

Document raster PROCESSING GAMMA option

---

de/mapfile/legend.txt
en/mapfile/legend.txt

See: https://github.com/MapServer/MapServer/pull/7154

MAX KEYSIZE = 1000

---

en/utilities/msencrypt.txt

Doc updates for https://github.com/MapServer/MapServer/pull/7181

Update notes about msencrypt and relative paths for 8.4

---

en/basemaps/install.txt

PBF is based on Google Protobuf. But saying here that it is a Google Format is misleading.

Improved wording

---

en/ogc/wms_server.txt

Document **ows_compliance_mode** introduced in https://github.com/MapServer/MapServer/pull/7280, https://github.com/MapServer/MapServer/pull/7284.

Document ows_compliance_mode
